# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-04 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20171204_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='wanttosay',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='我想说'),
        ),
        migrations.AlterField(
            model_name='info',
            name='create_date',
            field=models.CharField(default='2017-12-04 06:41:34', max_length=40, verbose_name='创建时间'),
        ),
    ]
