# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-04 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20171204_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='create_date',
            field=models.CharField(default='2017-12-04 07:51:04', max_length=40, verbose_name='创建时间'),
        ),
    ]
