# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-04 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20171204_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='PID',
            field=models.CharField(default='', max_length=150, verbose_name='身份证号'),
        ),
        migrations.AlterField(
            model_name='info',
            name='addr',
            field=models.CharField(default='', max_length=150, verbose_name='家庭住址'),
        ),
        migrations.AlterField(
            model_name='info',
            name='age',
            field=models.CharField(default='', max_length=150, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='info',
            name='contact',
            field=models.CharField(default='', max_length=150, verbose_name='联系方式'),
        ),
        migrations.AlterField(
            model_name='info',
            name='create_date',
            field=models.CharField(default='2017-12-04 13:00:54', max_length=40, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='info',
            name='education_background',
            field=models.CharField(default='', max_length=150, verbose_name='学历'),
        ),
        migrations.AlterField(
            model_name='info',
            name='ethnic',
            field=models.CharField(default='', max_length=150, verbose_name='民族'),
        ),
        migrations.AlterField(
            model_name='info',
            name='graduate_institutions',
            field=models.CharField(default='', max_length=150, verbose_name='毕业院校'),
        ),
        migrations.AlterField(
            model_name='info',
            name='health',
            field=models.CharField(default='', max_length=150, verbose_name='身体状况'),
        ),
        migrations.AlterField(
            model_name='info',
            name='major',
            field=models.CharField(default='', max_length=150, verbose_name='专业'),
        ),
        migrations.AlterField(
            model_name='info',
            name='marital_status',
            field=models.CharField(default='', max_length=150, verbose_name='婚姻状况'),
        ),
        migrations.AlterField(
            model_name='info',
            name='name',
            field=models.CharField(default='', max_length=150, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='info',
            name='native_place',
            field=models.CharField(default='', max_length=150, verbose_name='籍贯'),
        ),
        migrations.AlterField(
            model_name='info',
            name='political_role',
            field=models.CharField(default='', max_length=150, verbose_name='政治面貌'),
        ),
        migrations.AlterField(
            model_name='info',
            name='sex',
            field=models.CharField(default='', max_length=150, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='info',
            name='timeofwork',
            field=models.CharField(default='', max_length=150, verbose_name='参加工作时间'),
        ),
        migrations.AlterField(
            model_name='info',
            name='wanttosay',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='自我描述'),
        ),
        migrations.AlterField(
            model_name='info',
            name='wished_salary',
            field=models.CharField(default='', max_length=150, verbose_name='希望薪金/月'),
        ),
    ]
