# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-04 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20171204_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='create_date',
            field=models.CharField(default='2017-12-04 13:03:58', max_length=40, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='info',
            name='wanttosay',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='自我描述'),
        ),
    ]
