# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20171204_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='create_date',
            field=models.CharField(default='2017-12-04 13:08:26', max_length=40, verbose_name='创建时间'),
        ),
    ]
