# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20171204_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='create_date',
            field=models.CharField(default='2018-01-05 09:34:29', max_length=40, verbose_name='创建时间'),
        ),
    ]
