# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-17 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20180105_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='create_date',
            field=models.CharField(default='2018-05-17 08:26:10', max_length=40, verbose_name='创建时间'),
        ),
    ]
