# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-16 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20181016_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='create_date',
            field=models.CharField(default='2018-10-16 22:07:24', max_length=40, verbose_name='创建时间'),
        ),
    ]
