# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-16 15:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_auto_20181016_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=150, verbose_name='主题')),
                ('content', models.TextField(blank=True, max_length=1400, null=True, verbose_name='内容')),
                ('uuid', models.UUIDField(default=uuid.uuid4, verbose_name='uuid')),
                ('create_date', models.CharField(default='2018-10-16 23:01:38', max_length=40, verbose_name='创建时间')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='news',
            name='user',
        ),
        migrations.AlterField(
            model_name='info',
            name='create_date',
            field=models.CharField(default='2018-10-16 23:01:38', max_length=40, verbose_name='创建时间'),
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
