# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-17 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_auto_20181016_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='create_date',
            field=models.CharField(default='2018-10-17 11:07:10', max_length=40, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='new',
            name='create_date',
            field=models.CharField(default='2018-10-17 11:07:10', max_length=40, verbose_name='创建时间'),
        ),
    ]
