# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-18 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_auto_20181018_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='file_name',
            field=models.CharField(default='', max_length=150, verbose_name='文件名'),
        ),
        migrations.AlterField(
            model_name='info',
            name='create_date',
            field=models.CharField(default='2018-10-18 16:40:15', max_length=40, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='new',
            name='create_date',
            field=models.CharField(default='2018-10-18 16:40:15', max_length=40, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='upload_date',
            field=models.CharField(default='2018-10-18 16:40:15', max_length=40, verbose_name='创建时间'),
        ),
    ]
