# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-18 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_auto_20181018_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='news_photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Photo'),
        ),
        migrations.AlterField(
            model_name='info',
            name='create_date',
            field=models.CharField(default='2018-10-18 21:25:43', max_length=40, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='new',
            name='create_date',
            field=models.CharField(default='2018-10-18 21:25:43', max_length=40, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='upload_date',
            field=models.CharField(default='2018-10-18 21:25:43', max_length=40, verbose_name='创建时间'),
        ),
    ]
