# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-19 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_auto_20181019_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='module',
            field=models.CharField(default='qwe', max_length=150, verbose_name='所在模块'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='info',
            name='create_date',
            field=models.CharField(default='2018-10-19 21:35:21', max_length=40, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='new',
            name='create_date',
            field=models.CharField(default='2018-10-19 21:35:21', max_length=40, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='upload_date',
            field=models.CharField(default='2018-10-19 21:35:21', max_length=40, verbose_name='创建时间'),
        ),
    ]
